// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvhullovjqshiirvwwlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2aHVsbG92anFzaGlpcnZ3d2xtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NTk0NzIsImV4cCI6MjA3MzEzNTQ3Mn0.a-EiTHSbEU2qoi3BSntYnagTwKsSPXCaazf-GYFfPfo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});